server:
  port: 8830
  context-path: /
 
# 数据源配置
spring:
  
  application: 
    name: MICROSERVICE-EUREKA-STUDENT # 指定微服务应用名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    appname: microservice-eureka-student  #客户端服务名
    instance-id: microservice-eureka-student:8830 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      # 单机 
      #defaultZone: http://localhost:8881/eureka   #把服务注册到eureka注册中心
      # 集群
      defaultZone: http://eureka8881.steven.com:8881/eureka/,http://eureka8882.steven.com:8882/eureka/,http://eureka8883.steven.com:8883/eureka/ # 集群
                 
      
info: 
   groupId: com.steven.springcloud
   artifactId: microservice-eureka-student-provider-feign-hystrix-8830
   version: 1.0
   负责人: 张三
   联系电话: 110      
      
