server:
  port: 8850 
  context-path: /


spring:
  application:
    name: microservice-zuul


eureka:
  instance:
    instance-id: microservice-zuul:8850 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      defaultZone: http://eureka8881.steven.com:8881/eureka/,http://eureka8882.steven.com:8882/eureka/,http://eureka8883.steven.com:8883/eureka/ # 集群


zuul:
  ignored-services: "*"   # 屏蔽用微服务名进行请求，如屏蔽 http://zuul.steven.com:8850/microservice-eureka-student/student/list
  routes:
    studentServer.serviceId: microservice-eureka-student    # 指定要映射的微服务
    studentServer.path: /studentServer/**                   # 指定映射服务后的请求地址
  prefix: /steven                                           # 请求地址添加前缀  /steven


info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 王五
   联系电话: 110