server:
  port: 80
  context-path: /
  
eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
      defaultZone: http://eureka8881.steven.com:8881/eureka/,http://eureka8882.steven.com:8882/eureka/,http://eureka8883.steven.com:8883/eureka/